language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash

script:
    - phing -f build.xml full-build
